import { useEffect, useMemo, useState } from 'react';
import Room3D from './Room3D.jsx';
import Plan from './Plan.jsx';
import { catalog as demoCatalog, quote as demoQuote } from '../shared.js';
const pagesDemo = import.meta.env.VITE_PAGES_DEMO === 'true';

const DEFAULT = { roomW: 5.2, roomD: 4, roomH: 2.8, trackX: 0, trackZ: 0, trackL: 3.2, mount: 'surface', color: 'black', kelvin: 3000, brightness: 85, fixtures: [{ id: 1, type: 'spot', t: .18 }, { id: 2, type: 'spot', t: .5 }, { id: 3, type: 'wide', t: .82 }], selected: 2, view: '3d' };
const clamp = (n, a, b) => Math.min(b, Math.max(a, n));
const money = n => new Intl.NumberFormat('ru-RU').format(n) + ' ₽';
function readSaved() { try { const x = JSON.parse(localStorage.getItem('lights-prototype-v1')); return x && Array.isArray(x.fixtures) ? { ...DEFAULT, ...x } : DEFAULT; } catch { return DEFAULT; } }
const SectionHead = ({ number, title, subtitle }) => <div className="section-head"><span className="section-number">{number}</span><div><h2>{title}</h2><p>{subtitle}</p></div></div>;
function NumberField({ label, value, min, max, onChange }) { return <label className="number-field"><span>{label}</span><div><input type="number" min={min} max={max} step="0.1" value={value} onChange={e => onChange(clamp(Number(e.target.value) || min, min, max))} /><small>м</small></div></label>; }

export default function App() {
  const [project, setProject] = useState(readSaved);
  const [catalog, setCatalog] = useState(null);
  const [quote, setQuote] = useState(null);
  const [error, setError] = useState('');
  const [toast, setToast] = useState('');
  useEffect(() => { if (pagesDemo) { setCatalog(demoCatalog); return; } const controller = new AbortController(); fetch('/api/catalog', { signal: controller.signal }).then(r => { if (!r.ok) throw Error('Каталог недоступен'); return r.json(); }).then(setCatalog).catch(e => { if (e.name !== 'AbortError') setError(e.message); }); return () => controller.abort(); }, []);
  useEffect(() => { localStorage.setItem('lights-prototype-v1', JSON.stringify(project)); }, [project]);
  const quoteInput = useMemo(() => JSON.stringify({ mount: project.mount, trackL: project.trackL, fixtures: project.fixtures.map(f => ({ type: f.type })) }), [project.mount, project.trackL, project.fixtures]);
  useEffect(() => { if (!catalog) return; if (pagesDemo) { try { setQuote(demoQuote(JSON.parse(quoteInput))); setError(''); } catch (e) { setError(e.message); } return; } const controller = new AbortController(); fetch('/api/quote', { method: 'POST', headers: { 'content-type': 'application/json' }, body: quoteInput, signal: controller.signal }).then(async r => { const body = await r.json(); if (!r.ok) throw Error(body.error || 'Ошибка расчёта'); return body; }).then(data => { setQuote(data); setError(''); }).catch(e => { if (e.name !== 'AbortError') setError(e.message); }); return () => controller.abort(); }, [catalog, quoteInput]);
  const change = patch => setProject(p => ({ ...p, ...patch }));
  const setRoom = (key, value) => setProject(p => { const next = { ...p, [key]: value }; next.trackL = clamp(next.trackL, .8, Math.max(.8, next.roomW - .4)); next.trackX = clamp(next.trackX, -(next.roomW - next.trackL) / 2 + .2, (next.roomW - next.trackL) / 2 - .2); next.trackZ = clamp(next.trackZ, -next.roomD / 2 + .35, next.roomD / 2 - .35); return next; });
  const addFixture = type => setProject(p => { const id = Math.max(0, ...p.fixtures.map(f => f.id)) + 1; const slots = [.12, .28, .43, .57, .72, .88]; const t = slots.find(v => p.fixtures.every(f => Math.abs(f.t - v) > .1)) ?? .5; return { ...p, selected: id, fixtures: [...p.fixtures, { id, type, t }] }; });
  const updateSelected = type => setProject(p => ({ ...p, fixtures: p.fixtures.map(f => f.id === p.selected ? { ...f, type } : f) }));
  const removeSelected = () => setProject(p => { const fixtures = p.fixtures.filter(f => f.id !== p.selected); return { ...p, fixtures, selected: fixtures[0]?.id ?? null }; });
  const selected = project.fixtures.find(f => f.id === project.selected) ?? project.fixtures[0];
  const product = id => catalog?.fixtures.find(x => x.id === id);
  const flash = message => { setToast(message); setTimeout(() => setToast(''), 2800); };
  const download = () => { if (!quote) return; const lines = ['Проект трекового освещения', '', `Комната: ${project.roomW} × ${project.roomD} × ${project.roomH} м`, `Трек: ${project.trackL} м, ${project.color === 'black' ? 'чёрный' : 'белый'}, ${project.mount === 'surface' ? 'накладной' : 'встроенный'}`, `Свет: ${project.kelvin} K, яркость ${project.brightness}%`, '', 'Комплектация:', ...quote.items.map(item => `${item.name} — ${item.quantity} шт. × ${money(item.unitPrice)} = ${money(item.total)}`), '', `Итого: ${money(quote.total)}`, '', 'Демонстрационные товары и цены. Требуется подключение реального каталога.']; const blob = new Blob(['\ufeff' + lines.join('\n')], { type: 'text/plain;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'lighting-specification.txt'; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); };
  return <><header className="topbar"><div className="project-title"><strong>Конфигуратор освещения</strong><small>ПРОТОТИП · ТРЕКОВАЯ СИСТЕМА</small></div><div className="top-center">ПРОЕКТ ВАШЕЙ КОМНАТЫ</div><div className="header-actions"><button className="text-btn" onClick={() => { setProject(DEFAULT); flash('Проект сброшен'); }}>↺ <span>Начать заново</span></button><button className="outline-btn" onClick={() => flash('Проект сохранён в браузере')}>↧ <span>Сохранить проект</span></button></div></header>
    <main className="app-shell"><aside className="sidebar"><div className="sidebar-scroll"><div className="eyebrow">01 / ПАРАМЕТРЫ ПРОЕКТА</div><h1>Настройте<br /><em>свой свет.</em></h1><p className="intro">Спроектируйте систему под размеры вашей комнаты и сразу увидите результат.</p>
      <section className="section"><SectionHead number="01" title="Помещение" subtitle="Укажите размеры вашей комнаты" /><div className="dimension-grid"><NumberField label="Ширина" value={project.roomW} min={2} max={12} onChange={v => setRoom('roomW', v)} /><NumberField label="Глубина" value={project.roomD} min={2} max={12} onChange={v => setRoom('roomD', v)} /><NumberField label="Высота" value={project.roomH} min={2.2} max={5} onChange={v => setRoom('roomH', v)} /></div></section>
      <section className="section"><SectionHead number="02" title="Трековая система" subtitle="Настройте трек на потолке" /><div className="color-label">Тип монтажа</div><div className="mount-options">{(catalog?.tracks || [{ id: 'surface', name: 'Накладной трек', description: 'На поверхность потолка' }, { id: 'recessed', name: 'Встроенный трек', description: 'Вровень с потолком' }]).map(track => <button key={track.id} className={`mount-option ${project.mount === track.id ? 'active' : ''}`} onClick={() => change({ mount: track.id })}><strong>{track.id === 'surface' ? 'Накладной' : 'Встроенный'}</strong><small>{track.description}</small></button>)}</div><div className="color-label">Цвет профиля</div><div className="color-options"><button className={`color-option ${project.color === 'black' ? 'active' : ''}`} onClick={() => change({ color: 'black' })}><span className="swatch black" /> Чёрный <span className="check">✓</span></button><button className={`color-option ${project.color === 'white' ? 'active' : ''}`} onClick={() => change({ color: 'white' })}><span className="swatch white" /> Белый <span className="check">✓</span></button></div><div className="track-length"><label>Длина трека <strong>{project.trackL.toFixed(1)} м</strong></label><input id="trackL" type="range" min="0.8" max={Math.max(.8, project.roomW - .4)} step="0.1" value={project.trackL} onChange={e => setProject(p => ({ ...p, trackL: Number(e.target.value) }))} /><div className="range-ends"><span>0,8 м</span><span>{(project.roomW - .4).toFixed(1)} м</span></div></div><p className="tip">Перемещайте трек и светильники на плане потолка.</p></section>
      <section className="section fixtures-section"><SectionHead number="03" title="Светильники" subtitle="Добавьте приборы на трек" /><div className="catalog">{catalog?.fixtures.map(item => <button key={item.id} className="product-card" onClick={() => addFixture(item.id)}><span className="product-symbol">{item.icon}</span><span className="product-copy"><strong>{item.name}</strong><small>{item.type} · {item.watts} Вт</small></span><span className="product-price">{money(item.price)}</span><span className="product-add">+</span></button>) || <p className="empty-note">Загрузка каталога…</p>}</div></section>
      <section className="section atmosphere"><SectionHead number="04" title="Атмосфера" subtitle="Оцените характер света" /><div className="color-label">Температура света <strong>{project.kelvin} K</strong></div><input id="kelvin" className="warm-range" type="range" min="2700" max="5000" step="100" value={project.kelvin} onChange={e => change({ kelvin: Number(e.target.value) })} /><div className="range-ends"><span>Тёплый</span><span>Холодный</span></div><div className="track-length"><label>Яркость <strong>{project.brightness}%</strong></label><input id="brightness" type="range" min="10" max="100" step="5" value={project.brightness} onChange={e => change({ brightness: Number(e.target.value) })} /></div></section>
    </div></aside><div className="workspace"><div className="workspace-top"><div><div className="eyebrow">02 / ВАШЕ ПРОСТРАНСТВО</div><h2>Посмотрите, как это выглядит</h2></div><div className="view-switch"><button className={project.view === '3d' ? 'active' : ''} onClick={() => change({ view: '3d' })}>⬡ 3D-комната</button><button className={project.view === 'plan' ? 'active' : ''} onClick={() => change({ view: 'plan' })}>⊞ План потолка</button></div></div><div className="canvas-wrap">{project.view === '3d' ? <Room3D project={project} catalog={catalog} /> : catalog && <Plan project={project} catalog={catalog} setProject={setProject} />}<div className="scene-badge"><span className="live-dot" /> ПРЕДПРОСМОТР В РЕАЛЬНОМ ВРЕМЕНИ</div><div className="scene-hint">{project.view === '3d' ? 'Перетаскивайте, чтобы повернуть комнату · колесо — масштаб' : 'Перетаскивайте трек или светильники для настройки'}</div><div className="scene-corner">{project.roomW.toFixed(1)} × {project.roomD.toFixed(1)} м <span>·</span> h {project.roomH.toFixed(1)} м</div></div><div className="workspace-bottom"><div className="metric"><span>СВЕТИЛЬНИКИ</span><strong>{String(quote?.fixtureCount ?? project.fixtures.length).padStart(2, '0')}</strong></div><div className="metric"><span>СУММАРНАЯ МОЩНОСТЬ</span><strong>{quote?.watts ?? '—'} <small>Вт</small></strong></div><div className="metric"><span>СВЕТОВОЙ ПОТОК</span><strong>{quote ? new Intl.NumberFormat('ru-RU').format(quote.lumens) : '—'} <small>лм</small></strong></div><div className="metric note"><span>ВАЖНО</span><p>Свет в 3D — иллюстрация, не инженерный расчёт освещённости.</p></div></div></div>
      <aside className="summary"><div className="eyebrow">03 / РЕЗУЛЬТАТ</div><h2>Ваш проект</h2><p className="summary-sub">Комплектация рассчитывается сервером</p><div className="summary-visual"><div className="summary-line" />{project.fixtures.map(f => <span key={f.id} style={{ left: `${12 + f.t * 76}%` }}>{product(f.type)?.icon || '◉'}</span>)}</div><div className="summary-heading">СПЕЦИФИКАЦИЯ <span>{quote?.items.length ?? '—'} поз.</span></div><div className="summary-list">{quote?.items.map(item => <div className="spec-row" key={item.id}><span className="spec-icon">{product(item.id)?.icon || (item.id === 'power' ? '⌁' : '━')}</span><div><strong>{item.name}</strong><small>{item.description}</small></div><b>×{item.quantity}</b></div>)}</div><div className="selected-tools">{selected && catalog ? <><div className="selected-title">Выбранный светильник <span>#{project.fixtures.findIndex(f => f.id === selected.id) + 1}</span></div><div className="selected-row"><select value={selected.type} onChange={e => updateSelected(e.target.value)}>{catalog.fixtures.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select><button onClick={removeSelected} title="Удалить светильник">×</button></div></> : <p className="empty-note">Добавьте светильник слева.</p>}</div><div className="summary-total"><span>Предварительная стоимость</span><strong>{quote ? money(quote.total) : '—'}</strong><small>Демонстрационные цены. Не является офертой.</small><button className="primary-btn" disabled={!quote} onClick={download}>Скачать спецификацию <span>↗</span></button><p>{error || 'Проект автоматически сохраняется в этом браузере.'}</p></div></aside></main><div className={`toast ${toast ? 'show' : ''}`}>{toast}</div></>;
}
